name: Generate Dictionaries

on: workflow_dispatch

jobs:
  create:
    name: Generate Dictionaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1
      - name: Cache asdf
        id: cache-asdf
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-
      - name: Cache Poetry dependencies
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/python/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies in .tool-versions
        uses: asdf-vm/actions/install@v1
      - name: Run generators
        run: just freedict cedict ecdict
      - name: Add and commit to repo
        uses: EndBug/add-and-commit@v7
        with:
          add: "dictionaries"
          push: true
